---
superClass:
  FSNode:
    include:
      header:
      - FSNode
    includeClass:
      - Node
      - FSNode
      - CCBAnimationRegister
  FSButton::Listener:
    include:
      header:
      - FSButton
    includeClass:
    - FSButton::Listener
    # - CCBSelectorResolver
  FSScene:
    include:
      header:
      - FSScene
    includeClass:
      - Node
      - FSScene

  RequestBase:
    include:
      header:
      - RequestBase
    includeClass:
    - RequestBase
  Node:
    includeClass:
    - Node
  cocosbuilder::CCBMemberVariableAssigner:
    include:
      header:
      - Dialog
    includeClass:
    - cocosbuilder::CCBMemberVariableAssigner
method:
  Node:
    public:
    - virtual: 1
      static: 0
      return: void
      name: update
      args:
      - type: float
        name: dt
  FSNode:
    public:
    - virtual: 1
      static: 0
      return: void
      name: onStart
      args: []
    - virtual: 1
      static: 0
      return: void
      name: onEnd
      args: []
    - virtual: 1
      static: 0
      return: bool
      name: onRegisterVariable
      args:
      - type: Ref*
        name: pTarget
      - type: const char*
        name: name
      - type: Node*
        name: pNode
  FSScene:
    public:
    - virtual: 1
      static: 0
      return: void
      name: beginScene
      args: []
    - virtual: 1
      static: 0
      return: void
      name: endScene
      args: []
  FSButton:
    public:
    - virtual: 1
      static: 0
      return: void
      name: onStart
      args: []
    - virtual: 1
      static: 0
      return: void
      name: onEnd
      args: []
  FSButton::Listener:
    public:
    - virtual: 1
      static: 0
      return: bool
      name: onTap
      args:
      - type: FSButton*
        name: pButton
      - type: Touch*
        name: pTouch
    private:
    - virtual: 0
      static: 0
      return: void
      name: _setButtonListener
      args:
      - type: const char*
        name: name
      - type: Node*
        name: pNode
  CCBSelectorResolver:
    public:
    - virtual: 1
      static: 0
      return: SEL_MenuHandler
      name: onResolveCCBCCMenuItemSelector
      args:
      - type: Ref*
        name: pTarget
      - type: const char*
        name: name
    - virtual: 1
      static: 0
      return: SEL_CallFuncN
      name: onResolveCCBCCCallFuncSelector
      args:
      - type: Ref*
        name: pTarget
      - type: const char*
        name: name
    - virtual: 1
      static: 0
      return: cocos2d::extension::Control::Handler
      name: onResolveCCBCCControlSelector
      args:
      - type: Ref*
        name: pTarget
      - type: const char*
        name: name
  CCBAnimationRegister:
    public:
    # - virtual: 1
    #   static: 0
    #   return: SEL_CallFuncN
    #   name: onRegisterCallFunction
    #   args:
    #   - type: Ref*
    #     name: pTarget
    #   - type: const char*
    #     name: name
    - virtual: 1
      static: 0
      return: void
      name: completedAnimationSequenceNamed
      args:
      - type: const char*
        name: name
  cocosbuilder::CCBMemberVariableAssigner:
    public:
    - virtual: 1
      static: 0
      return: bool
      name: onAssignCCBCustomProperty
      args:
      - type: Ref*
        name: pTarget
      - type: const char*
        name: name
      - type: const Value&
        name: value
    - virtual: 1
      static: 0
      return: bool
      name: onAssignCCBMemberVariable
      args:
      - type: Ref*
        name: pTarget
      - type: const char*
        name: name
      - type: Node*
        name: pNode
  RequestBase:
    public:
    - virttual: 0
      static: 1
      return: $this$*
      name: create
      args: []
      context: '$t$$this$* obj = F10new($this$());$n$$t$obj->setKey();$n$$t$obj->setVal("1");$n$$t$return obj;$n$'



